sqlite:
  :adapter: sqlite
  :database: spec/url_field.sqlite.db

sqlite3:
  :adapter: sqlite3
  :database: spec/url_field.sqlite3.db

postgresql:
  :adapter: postgresql
  :username: postgres
  :password: postgres
  :database: url_field_test
  :min_messages: ERROR

mysql:
  :adapter: mysql
  :host: localhost
  :username: root
  :password: password
  :database: url_field_test